### ISSUE TITLE
Rename Runs from Run Info

### ISSUE THREAD

**Issue by QATCH-Technologies** [QATCH-Technologies/nanovisQ#13]
![Image](https://github.com/user-attachments/assets/54290c93-a124-45e2-949b-62b5513e38b8)

See attached screenshot. When attempting to rename a run from the Run Info dialog to something different, the new name is only reflected in the Run Info dialog view, but not in the dropdown list of available runs. This is suspected to be because the list of run names shown in the dropdown list is based on the folder name of the run, and not from the XML run name. It could also be a caching issue, and the "Rescan" button might update the name correctly. Depending on the cause, viable solutions could be to rename the folder too, the auto-rescan, and re-load the run under the new name; or, update the cached list of run names in the Analyze module when a run is renamed so that the dropdown menu will automatically reflect the new run name without having to re-parse the XML again.

**Comment by PaulMacNichol** [comment]
I may just have an incorrect/unexpected file structure but the Save button in the Run Info window does not seem to actually updating the filename at all.
As far as I can tell, the name in the filesystem is unchanged on edit.  So while rescanning shouldn't be too costly (as long as there are not too many runs), updating a run at all seems to be the first issue.

**Comment by PaulMacNichol** [comment]
Other sub-issues to address:
`mainWindow.py`
- Determine where the `data_files` attribute can be refreshed each time a file modification occurs.

`fileStorage.py`:
- What values constitute valid device folders?  Currently, any folders that are purely digits are returned but I am sure there is a more specific pattern to these folders than that.

`runInfo/update_run_names()`
- Determine which file suffixes to rename.  Should "__3rd.csv" files keep the "__3rd.csv" suffix or is this a convention specified by the user?
- Need to settle on a regex convention for valid file names.  Currently does not allow for spaces but can be modified to accommodate any pattern.
- Implement secure open to rewrite encrypted zip files.

**Comment by PaulMacNichol** [comment]
Going to close this out.  There are still some TODO tags but can be resolved later.
