### ISSUE TITLE
Refactor "Device Selection" to "Run Selection" in Advanced Settings

### ISSUE THREAD

**Issue by QATCH-Technologies** [QATCH-Technologies/nanovisQ#30]
![Image](https://github.com/user-attachments/assets/18935cde-088e-45db-9f4f-a41f94235cdf)

In the Analyze mode Advanced Settings menu:

- Rename "Device Selection" to "Run Selection"
- Rename "Device:" to "Show Only:"
- Rename "Show runs from all devices" to "Show all available runs"

These changes will be required once the "Configure Data" functionality is implemented to allow for custom folder structures.

**Comment by PaulMacNichol** [comment]
Updated relevant fields for new naming scheme.  Did we want to implement a more advanced search or just leave it as a dropdown?
